server:
  port: 10010

spring:
  application:
    name: CloudGateway
  cloud:
    gateway:
      routes:
        - id: user-provider # 路由ID， 必须唯一
          uri: lb://UserConsumer # 路由的目标地址，lb = Load Balance 负载均衡
          predicates:
            - Path=/consumer/** # 将/consumer/**请求转发到UserConsumer（/consumer/all）
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站进行跨域
              - "http://localhost:5731"
            allowed-methods: # 允许跨域的Ajax请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 跨域检测有效期
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


